language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

# Will only test on Linux be default, special includes are needed for OSX
python:
    - 2.7
    - 3.5
    - 3.6

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: osx
      language: generic
      env: PYTHON_VER=2.7
    - os: osx
      language: generic
      env: PYTHON_VER=3.5
    - os: osx
      language: generic
      env: PYTHON_VER=3.6

before_install:
  # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a
  # Install Pip or Conda and dependencies
  - source devtools/travis-ci/install.sh
  - python -V

install:
# Install the package locally
{% if (cookiecutter.dependency_source == 'conda-forge' or cookiecutter.dependency_source == 'conda') %}
    # Create test environment for package
  - conda create --yes -n test python=$PYTHON_VER pip pytest pytest-cov
  - source activate test
    {% if cookiecutter.dependency_source == "conda-forge" %}
  - conda install --yes codecov  # Only available in conda-forge channel or pip
    {% else %}
  - pip install codecov  # Only available in conda-forge channel or pip
    {% endif %}
    # Build and install package
  - conda build --python=$PYTHON_VER devtools/conda-recipe
  - conda install --yes --use-local {{cookiecutter.repo_name}}
{% elif cookiecutter.dependency_source == 'pip' %}
  - pip install -e .
{% endif %}

script:
  - pytest -v --cov={{cookiecutter.repo_name}} --cov-config setup.cfg {{cookiecutter.repo_name}}/tests/

notifications:
    email: false

after_success:
  - codecov