environment:

  matrix:
  {%- if (cookiecutter.dependency_source == 'Prefer conda-forge over the default anaconda channel with pip fallback' or cookiecutter.dependency_source == 'Prefer default anaconda channel with pip fallback') %}
    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
  {% elif cookiecutter.dependency_source == 'Dependencies from pip only (no conda)' %}
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
  {% endif %}

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  {% if (cookiecutter.dependency_source == 'Prefer conda-forge over the default anaconda channel with pip fallback' or cookiecutter.dependency_source == 'Prefer default anaconda channel with pip fallback') %}
  {%- if cookiecutter.dependency_source == 'Prefer conda-forge over the default anaconda channel with pip fallback' %}
    # Add conda-forge channel
  - conda config --add channels conda-forge
  {% endif %}

    # Always run commands without asking
  - conda config --set always_yes yes

    # Try to update conda first to avoid odd dependency clashes
  - conda update --all
  - conda install conda-build

    # Create test environment for package
  - conda create -n test python=%PYTHON_VERSION% pip pytest pytest-cov
  - activate test
    
    # Install any pip only modules
  - pip install codecov

    # Build and install package
  - conda build --quiet --python=%PYTHON_VERSION% devtools\\conda-recipe
  - conda install --use-local {{cookiecutter.repo_name}}
  {% elif cookiecutter.dependency_source == 'Dependencies from pip only (no conda)' %}
    # Install the package locally
  - pip install --upgrade pip setuptools
  - pip install pytest pytest-cov codecov
  - pip install -e .
  {% endif %}
build: false

test_script:
  - pytest -v --cov={{cookiecutter.repo_name}} {{cookiecutter.repo_name}}\\tests
